version: "3.9"
services:
  pwn-resolve:
    build:
      context: .
      args: 
        FLAG: "utflag{2_linker_problems_in_one_ctf?8079235}"
        USER: "resolve"
    ports:
      - "5435:9000"
    read_only: true
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 512M
        reservations:
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 5
