version: "3.8"
services:
  pwn-rop:
    build:
      context: .
      args: 
        FLAG: "utflag{ropalicious!329084}"
        USER: "rop"
    deploy:
      replicas: 1
    ports:
      - "1306:9000"
    read_only: true
