version: "3.8"
services:
  pwn-overflow:
    build:
      context: .
      args: 
        FLAG: "utflag{you_overflew_my_overflow091543}"
        USER: "overflow"
    deploy:
      replicas: 1
    ports:
      - "1302:9000"
    read_only: true
