version: "3.8"
services:
  pwn-overflow:
    build:
      context: .
      args: 
        FLAG: "utflag{o_no}"
        USER: "overflow"
    deploy:
      replicas: 1
    ports:
      - "5678:9000"
    read_only: true
